@ CrystalDust's furniture texts, restored in Phase 2 (D48).
Text_ItsATV:
	.string "It's a TV.$"

Text_MyReflection:
	.string "My reflection!\n"
	.string "Lookin' good!$"

Text_AncientPokemonReplica:
	.string "It's a replica of an ancient\n"
	.string "{POKEMON}.$"

Text_DistinguishedStatue:
	.string "A {POKEMON} statue…\n"
	.string "It looks very distinguished.$"

Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
